name: Deploy Vite React site to GitHub Pages

on:
  push:
    branches:
      - main   # 🚀 deploy when you push to main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Add CNAME file for custom domain
        run: echo "neuronecia.xyz" > dist/CNAME

      - name: Upload production-ready build
        uses: actions/upload-pages-artifact@v2
        with:
          path: dist   # Vite outputs to dist by default

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2

